use clap::{Arg, App};

pub fn create_mpwc_cli_app() -> App<'static,'static> {
  App::new("mpwc")
    .version("0.1.0")
    .author("Bryan G. <bryan@bryan.sh>")
    .about("Super duper simple Master Password CLI client. https://github.com/gilbertw1/mpwc")
    .arg(Arg::with_name("counter")
         .short("-c")
         .long("counter")
         .value_name("COUNTER")
         .help("Site counter")
         .takes_value(true)
         .default_value("1"))
    .arg(Arg::with_name("name")
         .short("-n")
         .long("name")
         .value_name("FULL_NAME")
         .help("Full name, defaults to environment variable $MPW_FULLNAME")
         .takes_value(true))
    .arg(Arg::with_name("prompt")
         .short("-p")
         .long("prompt")
         .help("If present prompts for master password, reads stdin otherwise"))
    .arg(Arg::with_name("site")
         .value_name("SITE")
         .help("Site to generate password for")
         .index(1)
         .required(true))
    .arg(Arg::with_name("type")
         .short("-t")
         .long("type")
         .value_name("TYPE")
         .help("Password type (max, long, medium, short, basic, pin), defaults to environment variable $MPW_SITETYPE")
         .takes_value(true)
         .default_value("max"))
}
